### ISSUE TITLE
USER STORY : Deployment

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#15]
In order to **make app available to the user** as a **developer**, I can **deploy app to heroku**

## Acceptance Criteria
* user is able to login/logout
* the app passes all  the basic acceptance criterion

# Tasks
- [ ] Create app 
- [ ] Update the configuration variables
- [ ] Connect to git hub repository
- [ ] Choose automatic deploys from github
- [ ] Deploy
- [ ] View build log
- [ ] Confirm deployment
