### ISSUE TITLE
Basic Skeleton setup

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#2]
In order to **create basic setup of the django application** as a **developer**, I can ** use django**

## Acceptance Criteria
* Django framework installed in gitpod successfully

# Tasks
- [ ]  Type install command in terminal 
- [ ]  Check for the directories in file area 
- [ ] Type install libraries commands in terminal
