### ISSUE TITLE
USER STORY : AllAuth

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#28]
As a developer, I need to Install allauth so that users can sign up and access to the app features

## Acceptance Criteria
* install is successful
* displays all the templates 

# Tasks
- [ ] Run server
- [ ] Create a new username
- [ ] Create a new password
- [ ] Login 
- [ ] Log out
- [ ] Add no email required to settings
