### ISSUE TITLE
USER STORY : Toasts

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#33]
As a **user ** I can **view success toasts** so that I can **preview shopping bag **
  
  
## Acceptance Criteria
* there's a grand total
* first column will contain the image
*  a paragraph for the items name
*  size if applicable
* quantity in bag
* the bag total
* notification about free delivery
* button which points at the view bag URL

# Tasks
- [x] add a little preview of the bag 
- [x] below threshold add free delivery delta  
- [x] tell them how much more they need to spend.
