### ISSUE TITLE
Manage Settings

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#4]
As a developer, I need to update the resources in settings so that images, style and scripts works on the website

## Acceptance Criteria
* the secret keys should be hidden

# Tasks
- [x] Set up environ variables
- [ ] Hide secret keys from git pod
- [x] Reference env.py
- [x] Update DataBases Sections
- [ ] Add Cloudinary Libraries to installed apps
- [ ] Tell Django to use Cloudinary to store media and static files
- [ ] Link file to the templates directory in Heroku
- [x] Change the templates directory to TEMPLATES_DIR
- [ ] Add Heroku Hostname to ALLOWED_HOSTS
