### ISSUE TITLE
USER STORY : Create  username

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/bouti#6]
In order to **check allauth install ** as a **developer**, I can **create a new username **

## Acceptance Criteria
* username is created successfully

# Tasks
- [ ] make a new username
- [ ] make a new password
- [ ] leave the email field blank
- [ ] runserver
- [ ]  check the home page
